INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripAllTrip', 'isFlight', 'label.SMTADT01.IsFlight', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "isflight","iconValue":"TRUE","iconOnly":true}]', 'text-center', 130, 'text-center', 'Radio'::dbo."filter_type", 'IsFlightList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);
INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripForApprove', 'isFlight', 'label.SMTADT01.IsFlight', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "isflight","iconValue":"TRUE","iconOnly":true}]', 'text-center', 130, 'text-center', 'Radio'::dbo."filter_type", 'IsFlightList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);
INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripMyDocument', 'isFlight', 'label.SMTADT01.IsFlight', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "isflight","iconValue":"TRUE","iconOnly":true}]', 'text-center', 130, 'text-center', 'Radio'::dbo."filter_type", 'IsFlightList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);
INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripAllTrip', 'isHotel', 'label.SMTADT01.IsHotel', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "ishotel","iconValue":"TRUE","iconOnly":true}]', 'text-center', 140, 'text-center', 'Radio'::dbo."filter_type", 'IsHotelList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);
INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripForApprove', 'isHotel', 'label.SMTADT01.IsHotel', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "ishotel","iconValue":"TRUE","iconOnly":true}]', 'text-center', 140, 'text-center', 'Radio'::dbo."filter_type", 'IsHotelList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);
INSERT INTO data_table_configulation
(company_code, table_name, column_name, column_label, "column_type", column_custom, column_align, column_sequence, header_align, "filter_type", filter_api, sort, display, active, created_by, created_date, created_program, updated_by, updated_date, updated_program)
VALUES('KNEX', 'TripMyDocument', 'isHotel', 'label.SMTADT01.IsHotel', 'Icon'::dbo."column_type", '[{"iconName": "check","iconLabel": "ishotel","iconValue":"TRUE","iconOnly":true}]', 'text-center', 140, 'text-center', 'Radio'::dbo."filter_type", 'IsHotelList', true, true, true, 'Procedure_Copy', '2025-04-01 16:10:31.011', 'Procedure_Copy', NULL, NULL, NULL);